---
- hosts: all
  become_user: root
  
  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /etc/ansible/pre.sh
      dest: /tmp/test
      remote_src: no
      owner: ans
      group: ans
      mode: '777
