---
- hosts: all
  become_user: root
  

  tasks:
  - name: Copy file with owner and permissions
    copy:
      src: /etc/ansible/test/pa.sh
      dest: /tmp/pa.sh
      remote_src: no
      owner: ans
      group: ans
      mode: '777'

