---
- hosts: all
  become: all
  
  tasks:
  - ping:
  - name: Check the OS- Release
    shell:
      cat /etc/os-release
    register: os_release
  - debug:
       var: os_release.stdout
  - name: Check For Package which requires upgarde
    yum:
      name: '*'
      latest: yes
      update_only: yes

    register: shellout
  - copy:
       content="{{ shellout.stdout }}"
       dest=/tmp/yumpreoutput
      
  - name: Reboot host and wait for it to restart
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
    
 
   
       
  
