---
- hosts: all
  become: all
  
  tasks:
  - ping:
  - name: Check the OS- Release
    shell:
      cat /etc/os-release
    register: os_release
  - debug:
       var: os_release.stdout
  - name: Check For Package which requires upgarde
    shell:
       yum check-update
    register: shellout
  - copy:
       content="{{ shellout.stdout }}"
       dest=/tmp/yumpreoutput
 
   
       
  
