---
- hosts: all
  become_user: root
  become: true

  tasks:

  - ping:

  - debug:
      msg: "Hostname - {{ ansible_hostname }} kernel_version - {{ ansible_kernel }}"

  - name: Current runnig procees
    shell: "ps -few"
    register: running_processoutput

  #- lineinfile:
      #line: " Hostname - {{ ansible_hostname }} {{running_processoutput}}"
      #path: /tmp/running_processoutput
    #delegate_to: localhost

  - copy:
      content:{{running_processoutput}}"
      dest:/tmp/current_process

  - name: precheck_script
    shell: ls -l /etc/sysconfig/network-scripts/ifcfg-*;cat /etc/sysconfig/network-scripts/ifcfg-*
    register: precheck_output
    
  
  
