---
- hosts: all
  become_user: root
  
  tasks:
  - name: List Security Updates
    shell:
      yum list-security --security
    register: shellout
  - debug:
       var: shellout 
      
         

  
