---
- hosts: all
  become_user: root
  
  tasks:
  -  name: shell script
     script: /etc/ansible/pre.sh
     
  -  name: List Security Updates
     shell:
       yum list-security --security
     register: shellout
     debug:
       var: shellout 
      
         

  
