---
- name: patching
  hosts: all
  become_user: root
  
  tasks:

  - ping:

  - debug:
      msg: "Hostname - {{ ansible_hostname }} kernel_version - {{ ansible_kernel }}"

  - name: list secirity
    shell:
      sudo  yum list-security --security
    register: precheck_security_output

  - debug:
      var: precheck_security_output

  - lineinfile:
      line: " Hostname - {{ ansible_hostname }} {{precheck_security_output.stdout}}"
      path: /tmp/precheck_security_output
    delegate_to: localhost
