---
- hosts: all
  become_user: root
  become: true

  tasks:

  - ping:

  - debug:
      msg: "Hostname - {{ ansible_hostname }} kernel_version - {{ ansible_kernel }}"

  - name: Current runnig procees
    shell: "ps -few"
    register: running_processoutput


  - name: precheck_script
    shell: ls -l /etc/sysconfig/network-scripts/ifcfg-*;cat /etc/sysconfig/network-scripts/ifcfg-*
    register: precheck_output
    
  
  
