---
- name: patching
  hosts: all
  become_user: root
  
  tasks:

  - ping:

  - debug:
      msg: "Hostname - {{ ansible_hostname }} kernel_version - {{ ansible_kernel }}"

  - name: Current runnig procees
    shell: "ps -few"
    register: running_processoutput

  - lineinfile:
      line: " Hostname - {{ ansible_hostname }} {{running_processoutput}}"
      path: /tmp/running_processoutput
    delegate_to: 10.128.0.2
