---
- hosts: all
  become_user: root
  
  tasks:
  - name: list secirity
    shell:
      yum list-security --security
    register: precheck_security_output

  - debug:
      var: precheck_security_output
      
         

  
