---
- name: patching
  hosts: all
  become_user: root
  

  tasks:

  - ping:

  - debug:
      msg: "Hostname - {{ansible_hostname}} Kernel_version - {{ansible_kernel}}"

  - name: restart system
    command: 
       sudo reboot
    register: reboot_started
    ignore_errors: true
  
  - name: Wait 300 seconds
    wait_for_connection:
      delay: 60
      timeout: 300
      
  - ping:
