---
- name: patching
  hosts: all
  become_user: root
  

  tasks:

  - ping:

  - debug:
      msg: "Hostname - {{ansible_hostname}} Kernel_version - {{ansible_kernel}}"

  - name: restart system
    command: 
       sudo reboot
    register: reboot_started
    ignore_errors: true


  - name: pause for 180 secs
    pause:
      minutes: 2


  - name: check if system responding to ssh
    local_action:
      module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=15
          timeout=300
          state=started

