---
- hosts: all
  become: true
  become_method: sudo
  become_user: root

  vars:
    - user1: { name: 'scot', comment: 'JAMES_SCOT'}

  tasks:
  - name: Adding User
    user:
      name: "{{ item.name }}"
      comment: "{{ item.comment }}"
    with_items:
      - "{{ user1 }}"
      - { name: 'mark', comment: 'MARK_JAMES }
dsd
